services:
  metastore:
    image: mysql:8.4
    hostname: metastore
    environment:
      MYSQL_ROOT_PASSWORD: jupyter
      MYSQL_DATABASE: hive_metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
    command: >
      --lower_case_table_names=1
      --explicit_defaults_for_timestamp=1
      --max_connections=512
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - metastore:/var/lib/mysql
      - ./metastore/ddl/init-hive-user.sql:/docker-entrypoint-initdb.d/init-hive-user.sql:ro
    networks:
      sparknet:
        ipv4_address: 172.28.1.1

  master:
    image: kjankiewicz/bigdata25-master:latest  # or :latest
    hostname: master
    depends_on:
      - metastore
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.2
      SPARK_LOCAL_HOSTNAME: master
      PYSPARK_PYTHON: /opt/venv/bin/python
      NAMEDIR: /opt/hadoop/dfs/name
      SPARK_LOGS_HDFS_PATH: /user/spark/logs
      SPARK_JARS_HDFS_PATH: /user/spark/jars
      HADOOP_CONF_DIR: /etc/hadoop/conf
      HIVE_CONF_DIR: /etc/hive/conf
      TEZ_CONF_DIR: /etc/tez/conf
      NM_WEBAPP_PORT: 8042
      DATANODE_HTTP_PORT: 9864
    ports:
      - "4040:4040" # Spark Driver UI
      - "8020:8020" # HDFS NameNode RPC port
      - "8088:8088" # YARN ResourceManager UI
      - "9870:9870" # HDFS NameNode Web UI
      - "9999:9999" # Tez UI (static files)
      - "10000:10000" # HiveServer2 (Thrift JDBC/Beeline)
      - "10002:10002" # Hive UI (e.g. HiveView)
      - "10005:10005" # Spark Thrift Server
      - "8888:8888"  # JupyterLab
      - "8188:8188"  # YARN Timeline Server (ATS) UI
      - "18080:18080"  # Spark History Server UI
      - "19888:19888"  # MR JobHistoryServer UI
    volumes:
      - namenode:/opt/hadoop/dfs/name
      - ./work:/home/hadoop
      - ./conf/hadoop:/etc/hadoop/conf:ro
      - ./conf/hive:/etc/hive/conf:ro
      - ./conf/tez:/etc/tez/conf:ro
      - ./conf/spark:/etc/spark/conf:ro
      - ./master/entrypoint.sh:/usr/local/sbin/entrypoint.sh:ro
    networks:
      sparknet:
        ipv4_address: 172.28.1.2

  worker1:
    image: kjankiewicz/bigdata25-worker:1.0.0
    hostname: worker1
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.3
      SPARK_LOCAL_HOSTNAME: worker1
      HADOOP_CONF_DIR: /etc/hadoop/conf
      HIVE_CONF_DIR: /etc/hive/conf
      TEZ_CONF_DIR: /etc/tez/conf
      NM_WEBAPP_PORT: 8042
      DATANODE_HTTP_PORT: 9864
    ports:
      - "8042:8042"
      - "9864:9864"
    volumes:
      - datanode1:/opt/hadoop/dfs/data
      - ./conf/hadoop:/etc/hadoop/conf:ro
      - ./conf/hive:/etc/hive/conf:ro
      - ./conf/tez:/etc/tez/conf:ro
      - ./worker/entrypoint.sh:/usr/local/sbin/entrypoint.sh:ro
    networks:
      sparknet:
        ipv4_address: 172.28.1.3

  worker2:
    image: kjankiewicz/bigdata25-worker:1.0.0
    hostname: worker2
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.4
      SPARK_LOCAL_HOSTNAME: worker2
      HADOOP_CONF_DIR: /etc/hadoop/conf
      TEZ_CONF_DIR: /etc/tez/conf
      NM_WEBAPP_PORT: 8043
      DATANODE_HTTP_PORT: 9865
    ports:
      - "8043:8043"
      - "9865:9865"
    volumes:
      - datanode2:/opt/hadoop/dfs/data
      - ./conf/hadoop:/etc/hadoop/conf:ro
      - ./conf/hive:/etc/hive/conf:ro
      - ./conf/tez:/etc/tez/conf:ro
      - ./worker/entrypoint.sh:/usr/local/sbin/entrypoint.sh:ro
    networks:
      sparknet:
        ipv4_address: 172.28.1.4

volumes:
  namenode:
  datanode1:
  datanode2:
  metastore:

networks:
  sparknet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
